version: '3.9'
services:
  next-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app
    command: sh -c "cd portfolio && npm run dev"
    ports:
      - "3000:3000"
    stdin_open: true 